version: '3'

services:
  pg:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
